### ISSUE TITLE
Lỗi rồi

### ISSUE THREAD

**Issue by obaviet** [quydang04/DirectAdmin_1.62.4#1]
Lỗi url [frees-da.vsicloud.com] rồi

**Comment by quydang04** [comment]
Mình vẫn cài bình thường nha bạn, bạn kiểm tra lại hộ mình nhé 
Link phải là: https://frees-da.vsicloud.com/services/ mới vào đc nha

**Comment by obaviet** [comment]
> Mình vẫn cài bình thường nha bạn, bạn kiểm tra lại hộ mình nhé Link phải là: https://frees-da.vsicloud.com/services/ mới vào đc nha

giờ cài ok rồi nhưng mới phát hiện ra là tính năng Multi Server không work
